# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Wod.create(title: '3 Rounds for time', description: ['800 m run', '30 pull-ups'])
Wod.create(title: '5 Rounds for time', description: ['20 sumo deadlift high-pull', '20 box jumps'])
Wod.create(title: '3 Rounds for time', description: ['800 m run', '10 strict bar muscle ups'])
Wod.create(title: 'AMRAP 10', description: ['10 squat cleans 155/105', '10 strict hspu'])
Wod.create(title: 'AMRAP 12', description: ['20 GHD sit-ups', '5 strict muscle-ups'])
Wod.create(title: '21-15-9', description: ['cleans', 'dips'])
Wod.create(title: '4 Rounds', description: ['400m run', '200m farmer carry'])
Wod.create(title: '3 Rounds', description: ['7 dumbell bench press', '5 strict L pull-ups', '1 mile run'])
Wod.create(title: 'AMRAP 20', description: ['5 power snatches', '7 toe-to-bars', '9 box jumps'])
Wod.create(title: '5 Rounds', description: ['20 wall balls', '10 deadlifts'])
Wod.create(title: '21-15-9', description: ['dumbell squat cleans', 'strict pull-ups', 'defict push-ups'])
Wod.create(title: 'Your choice', description: ['run 10,000m', 'or', 'row 10,000m'])
Wod.create(title: 'AMRAP 20', description: ['18 toe-to-bars', '10 dumbell hang clean and jerks'])
Wod.create(title: 'AMRAP 12', description: ['50 feet dumbell lunges', '16 toe-to-bars', '8 dumbell power cleans'])
Wod.create(title: '10 Rounds', description: ['9 thrusters', '35 double unders'])
Wod.create(title: '3 Rounds', description: ['50 m lunges AFSAP', '1 burpee per lunge'])
Wod.create(title: '3 Rounds', description: ['25 OHS 75/55', '15 T2B', '25/15 cal row', '15 burpee box jumps'])
Wod.create(category: 'Heroes', title: '3 Rounds', description: ['50 m lunges AFSAP', '1 burpee per lunge'])
Wod.create(category: 'Ladies', title: '21-15-9', description: ['thrusters', 'pull-ups'])
Wod.create(category: 'Ladies', title: 'AMRAP 20', description: ['5 pull-ups', '10 push-ups', '15 air squats'])
Wod.create(category: 'Ladies', title: '50-40-30-20-10 reps', description: ['double unders', 'sit-ups'])
Wod.create(category: 'Ladies', title: '10-9-8-7-6-5-4-3-2-1 reps', description: ['deadlift 1.5 bodyweight', 'bench press bodyweight', 'clean 3/4 bodyweight'])
Wod.create(category: 'Ladies', title: 'For Time', description: ['150 wall balls'])
Wod.create(category: 'Ladies', title: '5 Rounds', description: ['400m run', '15 overhead squats'])
Wod.create(category: 'Ladies', title: '3 Rounds', description: ['400m run', '21 kettlebell swings', '12 pull-ups'])
Wod.create(category: 'Ladies', title: 'For Time', description: ['30 snatches'])
Wod.create(category: 'Ladies', title: '5 Rounds', description: ['20 pull-ups', '30 push-ups', '40 sit-ups', '50 airsquats', '3 min rest'])
Wod.create(category: 'Ladies', title: 'For Time', description: ['100 pull-ups', '100 push-ups', '100 sit-ups', '100 air squats'])
Wod.create(category: 'Ladies', title: 'EMOM 30 Minutes', description: ['5 pull-ups', '10 push-ups', '15 air squats'])
Wod.create(category: 'Ladies', title: '21-15-9', description: ['deadlifts', 'handstand push-ups'])
Wod.create(category: 'Ladies', title: '21-15-9', description: ['cleans', 'ring dips'])
Wod.create(category: 'Ladies', title: 'AMRAP 20 Minutes', description: ['5 handstand push-ups', '10 pistols', '15 pull-ups'])
Wod.create(category: 'Ladies', title: '5 Rounds', description: ['800m run', '30 kettlebell swings', '30 pull-ups'])
Wod.create(category: 'Ladies', title: '9-7-5', description: ['muscle-ups', 'squat snatches'])
Wod.create(category: 'Ladies', title: '3 Rounds', description: ['50 air squats', '7 muscle-ups', '10 hang power cleans'])
Wod.create(category: 'Ladies', title: '5 Rounds', description: ['max bodyweight bench press', 'max pull-ups'])
Wod.create(category: 'Ladies', title: 'AMRAP 20', description: ['400m run', 'max pull-ups'])
Wod.create(category: 'Ladies', title: '5 Rounds', description: ['20 pull-ups', '40 push-ups', '60 air squats'])
Wod.create(category: 'Ladies', title: '5 Rounds', description: ['800m run', '15 dumbell thrusters', '15 pull-ups'])
Wod.create(category: 'Ladies', title: 'For Time', description: ['800m run', '50 thrusters', '30 pull-ups'])
Wod.create(category: 'Heroes', title: 'DT: 5 Rounds', description: ['12 deadlifts', '9 hang power cleans', '6 push jerks', 'all with same bar'])
Wod.create(category: 'Heroes', title: 'Murph: For Time', description: ['1 mile run', '100 pull-ups', '200 push-ups', '300 air squats', '1 mile run'])
Wod.create(category: 'Heroes', title: 'Zachary Tellier: For Time', description: ['10 burpees', '10 burpees, 25 push-ups', '10 burpees, 25 push-ups, 50 lunges', '10 burpees, 25 push-ups, 50 lunges, 100 sit-ups', '10 burpees, 25 push-ups, 50 lunges, 100 sit-ups, 150 air squats'])
Wod.create(category: 'Heroes', title: 'The Chief: Five 3-minute AMRAPS', description: ['3 power cleans', '6 push-ups', '9 air squats', 'rest 1 minute'])
Wod.create(category: 'Heroes', title: 'Kalsu: For Time', description: ['100 thrusters', '5 burpees to start and EMOM'])
Wod.create(category: 'Heroes', title: 'Holleyman: 30 Rounds', description: ['5 wall balls', '3 handstand push-ups', '1 power clean'])
Wod.create(category: 'Heroes', title: 'Randy: For Time', description: ['75 power snatches'])
Wod.create(category: 'Heroes', title: 'Bert: For Time', description: ['50 burpees', '400m run', '100 push-ups', '400m run', '150 walking lunges', '400m run', '200 air squats', '400m run', '150 walking lunges', '400m run', '100 push-ups', '400m run', '50 burpees'])
Wod.create(category: 'Heroes', title: 'The Don: For Time', description: ['66 deadlifts', '66 box jumps', '66 kettlebell swings', '66 knees-to-elbows', '66 sit-ups', '66 pull-ups', '66 thrusters', '66 wall balls', '66 burpees', '66 double unders'])
Wod.create(category: 'Heroes', title: 'Chris Kyle: 3 Rounds', description: ['40 kettlebell swings', '40 box jumps', '40 thrusters', '40 elevated push-ups'])
Wod.create(category: 'Heroes', title: 'Gaza: 5 Rounds', description: ['35 kettlebell swings', '30 push-ups', '25 pull-ups', '20 box jumps', '1 mile run'])
Wod.create(category: 'Heroes', title: 'JT: 21-15-9', description: ['handstand push-ups', 'ring dips', 'push-ups'])
Wod.create(category: 'Heroes', title: 'Zeus: 3 Rounds', description: ['30 wall balls', '30 sumo deadlifts', '30 box jumps', '30 push presses', '30 cal row', '30 push-ups', '10 back squats'])
Wod.create(category: 'Heroes', title: 'Hotshots 19: 6 Rounds', description: ['30 air squats', '19 power cleans', '7 strict pull-ups', '400m run'])


